-- 表属性配置表
CREATE TABLE IF NOT EXISTS `table_attribute` (
  `tableName` varchar(100) COMMENT '数据库中文表名',
  `dbtable` varchar(100) NOT NULL COMMENT '数据库表名',
  `sort` varchar(200) COMMENT '排序内容',
  `functions` varchar(100) COMMENT '功能模块',
  `groupby` varchar(200) COMMENT '分组排序',
  `isLoading` tinyint(1) DEFAULT 0 COMMENT '是否显示进度,0-否,1-是',
  `isAllSelect` tinyint(1) DEFAULT 0 COMMENT '是否全选,0-否,1-是',
  `isRowOpertionFlag` tinyint(1) DEFAULT 0 COMMENT '是否行操作,0-否,1-是',
  `isOpertionFlag` tinyint(1) DEFAULT 0 COMMENT '是否操作,0-否,1-是',
  `tableProcedure` varchar(100) COMMENT '存储过程名',
  `subTables` varchar(200) COMMENT '子表名称',
  `tableKey` varchar(100) COMMENT '主从表关联字段',
  `ParameterType` tinyint(1) COMMENT '参数类型',
  `alias` varchar(100) COMMENT '其它名称',
  `mainKey` varchar(100) COMMENT '表关键字段名称',
  `pageTitle` varchar(100) COMMENT '页面标题',
  `roleFlag` tinyint(1) DEFAULT 0 COMMENT '是否角色控制,0-否,1-是',
  `joinStr` varchar(500) COMMENT '关联',
  `definColumns` varchar(500) COMMENT '自定义字段',
  PRIMARY KEY (`dbtable`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='表属性配置表';

-- 字段属性配置表
CREATE TABLE IF NOT EXISTS `column_attribute` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dbTableName` varchar(100) NOT NULL COMMENT '数据库表名',
  `tableName` varchar(100) COMMENT '数据库中文表名',
  `name` varchar(100) NOT NULL COMMENT '字段名称',
  `pagename` varchar(100) COMMENT '名称',
  `IsShowInList` tinyint(1) DEFAULT 0 COMMENT '列表显示,0-否,1-是',
  `searchFlag` tinyint(1) DEFAULT 0 COMMENT '查询,0-否,1-是',
  `editFlag` tinyint(1) DEFAULT 0 COMMENT '编辑,0-否,1-是',
  `options` varchar(50) COMMENT '选择数据,0-字典,1-autoselect,2-本身',
  `showType` varchar(50) COMMENT '控件类型',
  `queryType` varchar(50) COMMENT '匹配方式',
  `checkMode` varchar(50) COMMENT '校验方式',
  `IsRequired` tinyint(1) DEFAULT 0 COMMENT '必填,0-否,1-是',
  `autoSelectId` int(11) COMMENT '下拉框属性',
  `OrderNo` int(11) COMMENT '字段排序',
  `searchOrderNo` int(11) COMMENT '搜索排序',
  `editOrderNo` int(11) COMMENT '编辑排序',
  `defaultValue` varchar(200) COMMENT '默认值',
  `len` int(11) COMMENT '字段长度',
  `fieldType` varchar(50) COMMENT '字段类型',
  `type` int(11) COMMENT '字段类型',
  `classcode` varchar(100) COMMENT '字典代码',
  `Other` varchar(200) COMMENT '其它',
  `isRead` tinyint(1) DEFAULT 0 COMMENT '只读,0-否,1-是',
  `unionTable` varchar(100) COMMENT '外部关联表名',
  `IsPri` tinyint(1) DEFAULT 0 COMMENT '主键,0-否,1-是',
  `IsForeignKey` tinyint(1) DEFAULT 0 COMMENT '其它主键,0-否,1-是',
  `attrType` varchar(50) COMMENT '属性类型',
  `attrName` varchar(100) COMMENT '属性名称',
  `whereSql` varchar(500) COMMENT '自订义条件',
  `templetResId` int(11) COMMENT '模板ID',
  `selectColumns` varchar(500) COMMENT '外联表字段列',
  `isExport` tinyint(1) DEFAULT 0 COMMENT '导出,0-否,1-是',
  `showWidth` int(11) COMMENT '显示宽度',
  `contentLen` int(11) COMMENT '内容长度',
  `editType` varchar(50) COMMENT '编辑属性',
  `roles` varchar(200) COMMENT '角色名称',
  `importRequired` tinyint(1) DEFAULT 0 COMMENT '导出必填',
  `searchWidth` int(11) COMMENT '搜索宽度',
  `listWidth` int(11) COMMENT '列表宽度',
  `isBatch` tinyint(1) DEFAULT 0 COMMENT '是否批量,0-否，1-是',
  `isMobile` tinyint(1) DEFAULT 0 COMMENT '是否手机端',
  PRIMARY KEY (`id`),
  KEY `idx_dbtable_name` (`dbTableName`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字段属性配置表';

-- 字段校验属性表
CREATE TABLE IF NOT EXISTS `column_check_property` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `check_table` varchar(100) NOT NULL COMMENT '表名',
  `check_column` varchar(100) NOT NULL COMMENT '校验字段名',
  `check_mode` varchar(50) NOT NULL COMMENT '校验方式',
  `status` tinyint(1) DEFAULT 1 COMMENT '状态，0-无效，1-有效',
  `errorMsg` varchar(200) COMMENT '提示信息',
  `whereStr` varchar(500) COMMENT '过滤条件语句',
  `paraColumn` varchar(100) COMMENT '参数列名',
  PRIMARY KEY (`id`),
  KEY `idx_table_column` (`check_table`,`check_column`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字段校验属性表';

-- 自动选择配置表
CREATE TABLE IF NOT EXISTS `autoselect` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自动增长主键',
  `tableName` varchar(100) NOT NULL COMMENT '数据库表名',
  `name` varchar(100) COMMENT '名称',
  `formSql` varchar(500) COMMENT '自定义查询表',
  `selectSql` varchar(500) COMMENT '自定义查询列名',
  `whereSql` varchar(500) COMMENT '自定义筛选条件',
  `isEnable` tinyint(1) DEFAULT 1 COMMENT '是否有效',
  `Type` tinyint(1) COMMENT '类型,0-整型,1-字符,2-范围',
  `description` varchar(200) COMMENT '描述',
  `columnatrribleID` int(11) COMMENT '属性表字段id',
  `orderbySql` varchar(200) COMMENT '排序',
  `groupbySql` varchar(200) COMMENT '分组',
  `dbSrc` varchar(100) COMMENT '数据源名',
  `pageSize` int(11) COMMENT '每页数量',
  `columnChar` varchar(100) COMMENT '字符查询的字段名',
  `columnInt` varchar(100) COMMENT '整数查询的字段名',
  `columnOther` varchar(100) COMMENT '其它类型的查询字段名',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动选择配置表';
