server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://www.ycbd.work:3306/smbservice?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ycbd
    password: Ycbd74mysql!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ycbd.demo: debug
jwt:
  secret: ycbd
  expire-time: 86400000  # 24小时